resolver: lts-19.1

packages:
- .

extra-deps:
- git: https://gitlab.imn.htwk-leipzig.de/waldmann/begriff.git
  commit: b23e7a9b795ae276a5db1bf1077a0f2786d79870

system-ghc: true
compiler-check: newer-minor
