module Handler.LegacyListHiddenCompetitions where

import Import
import Handler.ListHiddenCompetitions

getLegacyListHiddenCompetitionsR :: Handler Html
getLegacyListHiddenCompetitionsR = getListHiddenCompetitionsR
